[build]
  base = ""
  command = "npm run build"
  publish = ""

[build.environment]
  NODE_VERSION = "20.20.0"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions"
