name = "eltx-hub"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd frontend && npm run build"
cwd = "."
watch_dir = "frontend"

[env.production]
name = "eltx-hub-prod"

[env.preview]
name = "eltx-hub-preview"
